# Overrides for examples/dpraco_heart_false_negative_rate_demo.ipynb
training_params:
  target_epsilon: 1.0
  seed: 2189
  number_of_steps: 1000
  batch_size: 1024
  lr_lambda: 0.5
  softmax_temperature: 1
  lr: 0.1
  momentum: 0

algorithm:
  gamma: 0.25
  C: 30
  laplace_parameter_b: 0.1
